Name:           ros-indigo-moveit-ros-move-group
Version:        0.7.2
Release:        0%{?dist}
Summary:        ROS moveit_ros_move_group package

Group:          Development/Libraries
License:        BSD
URL:            http://moveit.ros.org
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-actionlib
Requires:       ros-indigo-moveit-core
Requires:       ros-indigo-moveit-ros-planning
Requires:       ros-indigo-pluginlib
Requires:       ros-indigo-std-srvs
Requires:       ros-indigo-tf
BuildRequires:  ros-indigo-actionlib
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-moveit-core
BuildRequires:  ros-indigo-moveit-ros-planning
BuildRequires:  ros-indigo-pluginlib
BuildRequires:  ros-indigo-std-srvs
BuildRequires:  ros-indigo-tf

%description
The move_group node for MoveIt

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Jun 20 2016 Sachin Chitta <robot.moveit@gmail.com> - 0.7.2-0
- Autogenerated by Bloom

* Tue Apr 12 2016 Sachin Chitta <robot.moveit@gmail.com> - 0.7.1-0
- Autogenerated by Bloom

* Sat Jan 30 2016 Sachin Chitta <robot.moveit@gmail.com> - 0.7.0-0
- Autogenerated by Bloom

* Sat Jan 24 2015 Sachin Chitta <robot.moveit@gmail.com> - 0.6.5-0
- Autogenerated by Bloom

* Sat Dec 20 2014 Sachin Chitta <robot.moveit@gmail.com> - 0.6.4-0
- Autogenerated by Bloom

* Thu Dec 04 2014 Sachin Chitta <robot.moveit@gmail.com> - 0.6.3-0
- Autogenerated by Bloom

* Fri Oct 31 2014 Sachin Chitta <robot.moveit@gmail.com> - 0.6.2-0
- Autogenerated by Bloom

* Fri Oct 31 2014 Sachin Chitta <robot.moveit@gmail.com> - 0.6.1-0
- Autogenerated by Bloom

* Mon Oct 27 2014 Sachin Chitta <robot.moveit@gmail.com> - 0.6.0-0
- Autogenerated by Bloom

