Name:           ros-jade-moveit-ros-planning-interface
Version:        0.6.5
Release:        0%{?dist}
Summary:        ROS moveit_ros_planning_interface package

Group:          Development/Libraries
License:        BSD
URL:            http://moveit.ros.org
Source0:        %{name}-%{version}.tar.gz

Requires:       python-devel
Requires:       ros-jade-actionlib
Requires:       ros-jade-eigen-conversions
Requires:       ros-jade-moveit-ros-manipulation
Requires:       ros-jade-moveit-ros-move-group
Requires:       ros-jade-moveit-ros-planning
Requires:       ros-jade-moveit-ros-warehouse
Requires:       ros-jade-rosconsole
Requires:       ros-jade-roscpp
Requires:       ros-jade-rospy
Requires:       ros-jade-tf
Requires:       ros-jade-tf-conversions
BuildRequires:  python-catkin_pkg
BuildRequires:  python-devel
BuildRequires:  ros-jade-actionlib
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-cmake-modules
BuildRequires:  ros-jade-eigen-conversions
BuildRequires:  ros-jade-moveit-ros-manipulation
BuildRequires:  ros-jade-moveit-ros-move-group
BuildRequires:  ros-jade-moveit-ros-planning
BuildRequires:  ros-jade-moveit-ros-warehouse
BuildRequires:  ros-jade-rosconsole
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-rospy
BuildRequires:  ros-jade-tf
BuildRequires:  ros-jade-tf-conversions

%description
Components of MoveIt that offer simpler interfaces to planning and execution

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Thu May 14 2015 Ioan Sucan <isucan@google.com> - 0.6.5-0
- Autogenerated by Bloom

